### ISSUE TITLE
startTrackerWithId not working with 1.8.3 or 1.8.6 for Android

### ISSUE THREAD

**Issue by alfredteo36** [danwilson/google-analytics-plugin#536]
Ionic Info

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (C:\Users\Alfred\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.3.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Program Files (x86)\Android\android-sdk)
   NodeJS            : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.0
   OS                : Windows 10

Google Analytics: 1.8.3

Android Studio Debug Log

System.err: java.lang.NoClassDefFoundError: com.google.android.gms.common.internal.zzbo
08-24 15:22:20.300 6209-6321/ W/System.err:     at com.google.android.gms.internal.zzami.zzaf(Unknown Source)
        at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source)
        at com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin.startTracker(UniversalAnalyticsPlugin.java:145)
        at com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin.execute(UniversalAnalyticsPlugin.java:53)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
08-24 15:22:20.301 6209-6321/ W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by alexlopezit** [comment]
+1

**Comment by manelds** [comment]
+2

**Comment by terpro** [comment]
Same issue here

**Comment by manelds** [comment]
If use GMS on version 11.0.1 it works, but in my case, in order to make compatible the FCM plugin and this plugin, I set the the GMS_VERSION to 9.0.0.

Resume:
[WORK]       =>  ionic cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=11.0.1
[NO WORK] =>  ionic cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=9.0.0

**Comment by spinninghamster** [comment]
I also have this problem.

**Comment by guilhermegjr** [comment]
+1

**Comment by malwatte** [comment]
+1

**Comment by malwatte** [comment]
I changed the gms version to 16.0.3 and it started to work
`cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=16.0.3`
I use latest version of phonegap-push-plugin too.
Check other plugins and change the GMS_VERSION version accordingly

**Comment by spinninghamster** [comment]
> I changed the gms version to 16.0.3 and it started to work
> `cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=16.0.3`
> I use latest version of phonegap-push-plugin too.
> Check other plugins and change the GMS_VERSION version accordingly

That fixed it for me.

**Comment by ansarikhurshid786** [comment]
Thanks. 
ionic cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=16.0.3

this command is working for me.

**Comment by vespino** [comment]
How can I fix this issue on Phonegap Build?

**Comment by selected-pixel-jameson** [comment]
Do you need to remove and re-add the plugins or the entire android platform after the below command? 
```ionic cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=16.0.3```

I can't get it to start the tracker even after I make that update.

**Comment by terpro** [comment]
@selected-pixel-jameson can you compile? Try `cordova clean`

**Comment by selected-pixel-jameson** [comment]
@terpro Nope. That doesn't help. And from what I've seen if I remove the android project and re-add it and all the plugins then the app crashes outright upon the initial launch.

**Comment by selected-pixel-jameson** [comment]
Oh and if I try to revert this back to 1.8.3 then the app also just crashes out right when launching.

**Comment by selected-pixel-jameson** [comment]
It appears as if there is some kind of conflict going on here with the OneSignal and Google Analytics plugins.

**Comment by shraddha-R** [comment]
GoogleAnalytics.startTrackerWithId is not a function with 1.8.6. 
Not able to start analytics. Any solution to this pls.

**Comment by vijayan007** [comment]
> cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=16.0.3

What is the Capacitor Equivalent of this?

**Comment by vijayan007** [comment]
- Updated in this file - `app/node_modules/cordova-plugin-google-analytics/plugin.xml`
- Line 46: `<preference name="GMS_VERSION" default="16.0.3"/>`
